// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    // Use fallback for prisma generate (doesn't connect to DB)
    url: process.env.DATABASE_URL ?? "postgresql://localhost:5432/placeholder",
  },
});
