export const EXCEL_CONSTANTS = {
  MAX_FILE_SIZE: 10 * 1024 * 1024,
  BATCH_SIZE: 100,
  MAX_ROWS: 10000,
  HEADERS: {
    TITLE: 'Title',
    DESCRIPTION: 'Description',
    CATEGORY_ID: 'Category ID',
    PRICE: 'Price',
    ORIGINAL_PRICE: 'Original Price',
    CONDITION: 'Condition',
    LOCATION: 'Location',
    STOCK: 'Stock',
    MIN_STOCK: 'Min Stock',
    MAX_STOCK: 'Max Stock',
    COST_PRICE: 'Cost Price',
    SELLING_PRICE: 'Selling Price',
    SKU: 'SKU',
    BARCODE: 'Barcode',
    TAGS: 'Tags',
    BADGES: 'Badges',
    STORE_ID: 'Store ID',
  },
  CONDITION_VALUES: ['new', 'like_new', 'good', 'fair', 'poor'],
  BADGE_VALUES: ['NEW', 'FEATURED', 'PROMO', 'HOT', 'SALE'],
} as const;
